# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres:16
    container_name: db
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
    # ports:
    #   - 5432:5432

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db

  fastapi:
    build: ./fastapi
    container_name: fastapi
    restart: always
    # ports:
    #   - 8000:8000
    working_dir: /app
    volumes:
      - ./fastapi:/app
    command: bash -c "python3 main.py"
    depends_on:
      - db

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - 8000:8000
      - 3000:3000
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      # - ./nginx/logs:/var/log/nginx
    depends_on:
      - fastapi
      - frontend

  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    # ports:
    # - 3000:3000
    working_dir: /app
    volumes:
      - ./frontend:/app
    # command: bash -c "npm run dev"
    command: bash -c "npm install && npm run build && npm run start"
    depends_on:
      - fastapi
